### PR TITLE
[FEATURE]: Triggering Github refresh job via Ingestion API.

### PR DESCRIPTION
**Pull request by jparsai**
# Description 
Using Ingestion API to trigger worker flow instead of embedded code, also enabled Golang refresh jobs.
Modified test cases and cleaned up dependencies.

# Ticket
APPAI-1654

### CODE REVIEW

**Comment by yzainee-zz** [comment]
normal github refresh job runs only selective flows. i dont see that logic here. can you please explain the behaviour for golang vs other ecosystems in this regard.

**Comment by jparsai** [comment]
Yes, this is also selective ingestion. Here '**ingestions/epv-selective**' end point is called which is having logic to trigger a partial run according to flow name and task list provided. For full ingestion e use '**ingestions/epv**'.

**Comment by jparsai** [comment]
Here is the API spec for more details about Ingestion API end points.
https://app.swaggerhub.com/apis/jparsai/Jobs_API/0.1#/

**Comment by yzainee-zz** [comment]
Can you please rename the env variable in that case. It causes confusion as its says ingestion api. you can rename to something like selective ingestion api

**Review by yzainee-zz — APPROVED** [review]
LGTM

**Pull request merged**
