### PR TITLE
Updating the dependencies to latest versions.

### PR DESCRIPTION
**Pull request by jparsai**

### CODE REVIEW

**Review by arajkumar — CHANGES_REQUESTED** [review]
This is incorrect. These has to go into requirements.in & generate the requirements.txt using pip-compile. Also this mandates the proper way to onboard selinon with our changes.

**Comment by jparsai** [comment]
Okay @arajkumar I will update in requirements.in.
Some confusion has been there, on channel during our conversation you said in last message that for time being I can update in requirements.txt so I did here, so I thought later I will update requirement.in and do it through setup.py.

**Comment by jparsai** [comment]
@arajkumar that is the doubt I was referring to on channel.
As of now we are installing Selinon package through binary and we discussed earlier it is not right way and it has to be installed from Github link, which is not there yet.
I tried to fork Selinon repo in fabric8-analytics project but I dont have permission to do that. As you are member of project can you please fork it? or is there any other way I can push Selinon repo on fabric8-analytics?

**Comment by arajkumar** [comment]
@jparsai Just forked Selinon into our org. Please make use of it.
https://github.com/fabric8-analytics/selinon

**Pull request closed without merging**
